"""Weights & Biases experiment tracking wrapper.

Default mode: **offline** (WANDB_MODE=offline) to avoid accidental data leak.
Users must explicitly pass ``mode="online"`` or ``--wandb-online`` to upload.

When wandb is not installed (e.g. inference-only environment), all
WandbLogger methods become no-ops. Training scripts can call them
unconditionally without try/except.
"""

from __future__ import annotations

import contextlib
import os
from pathlib import Path
from typing import Any, Literal

# Optional dependency
try:
    import wandb as _wandb

    WANDB_AVAILABLE = True
except ImportError:
    WANDB_AVAILABLE = False
    _wandb = None  # type: ignore[assignment]


class WandbLogger:
    """Wandb experiment tracker.

    When wandb is not installed or ``mode="disabled"``, all methods are no-ops.

    Parameters
    ----------
    project:
        Wandb project name (default ``"aurumq-rl"``).
    run_name:
        Run name (None → auto-generated by wandb).
    config:
        Hyperparameters dict, written to wandb run config.
    mode:
        ``"offline"`` (default) — local logging only, no upload.
        ``"online"``  — realtime upload to wandb cloud (needs wandb login).
        ``"disabled"`` — fully disabled (same as wandb not installed).
    out_dir:
        WANDB_DIR path; None uses wandb default (~/.wandb or ./wandb).
    """

    def __init__(
        self,
        project: str = "aurumq-rl",
        run_name: str | None = None,
        config: dict[str, Any] | None = None,
        mode: Literal["online", "offline", "disabled"] = "offline",
        out_dir: Path | None = None,
    ) -> None:
        self.enabled = False
        self._run: Any = None

        if not WANDB_AVAILABLE or mode == "disabled":
            return

        os.environ["WANDB_MODE"] = mode
        if out_dir is not None:
            os.environ["WANDB_DIR"] = str(out_dir)

        try:
            self._run = _wandb.init(
                project=project,
                name=run_name,
                config=config or {},
                reinit=True,
            )
            self.enabled = True
        except Exception:
            self.enabled = False

    def log_metrics(self, metrics: dict[str, Any], step: int) -> None:
        """Log a batch of metrics at the given step."""
        if not self.enabled:
            return
        with contextlib.suppress(Exception):
            _wandb.log(metrics, step=step)

    def log_artifact(
        self,
        path: Path,
        name: str,
        artifact_type: str = "model",
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Upload a file or directory as a wandb artifact."""
        if not self.enabled:
            return
        if not Path(path).exists():
            return
        try:
            artifact = _wandb.Artifact(name=name, type=artifact_type, metadata=metadata or {})
            p = Path(path)
            if p.is_dir():
                artifact.add_dir(str(p))
            else:
                artifact.add_file(str(p))
            _wandb.log_artifact(artifact)
        except Exception:
            pass

    def log_config(self, config: dict[str, Any]) -> None:
        """Update wandb run config."""
        if not self.enabled:
            return
        with contextlib.suppress(Exception):
            _wandb.config.update(config, allow_val_change=True)

    def finish(self) -> None:
        """End current wandb run (idempotent)."""
        if not self.enabled:
            return
        try:
            _wandb.finish()
        except Exception:
            pass
        finally:
            self.enabled = False

    def __enter__(self) -> WandbLogger:
        return self

    def __exit__(self, *args: Any) -> None:
        self.finish()

    def __repr__(self) -> str:
        status = "enabled" if self.enabled else "disabled"
        return f"WandbLogger(status={status!r})"


__all__ = ["WANDB_AVAILABLE", "WandbLogger"]
